name: main
on: [push]

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: card
      - uses: actions/checkout@v2
        with:
          repository: fahien/gfxspot
          path: gfx
      - uses: actions/checkout@v2
        with:
          repository: fahien/gltfspot
          path: gltf
      - uses: actions/checkout@v2
        with:
          repository: fahien/mathspot
          path: math
      - uses: actions/checkout@v2
        with:
          repository: fahien/filespot
          path: file

      - name: conan
        run: pip install conan

      - name: vulkan
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe" -OutFile vulkan-sdk.exe
          7z x ./vulkan-sdk.exe -ovulkan-sdk

      - name: gen
        run: |
          $env:VULKAN_SDK="$pwd\vulkan-sdk"
          $env:Path+=";$env:VULKAN_SDK\Bin"
          cmake -Scard -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: build
        run: cmake --build build --config Release --target client-cardspot --target shaders --parallel
