name: main
on: [push]

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@master
        with:
          name: gfx
          repository: fahien/gfxspot
      - uses: actions/checkout@master
        with:
          name: gltf
          repository: fahien/gltfspot
      - uses: actions/checkout@master
        with:
          name: math
          repository: fahien/mathspot

      - name: gen
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: build
        run: cmake --build build -- -j4
